name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install dependencies
        run: yarn
      - name: Build reporter
        run: yarn build
      - name: Run tests
        id: run-tests
        run: yarn test
      - name: Report Metrics
        if: always()
        uses: masci/datadog@v1
        with:
          api-key: ${{ secrets.DATADOG_API_KEY }}
          metrics: |
            - type: "count"
              name: "some_project_or_repo.tests.count"
              value: ${{steps.run-tests.outputs.numTotalTests}}
              host: ${{ github.repository_owner }}
              tags:
                - "project:${{ github.repository }}"
                - "branch:${{ github.head_ref }}"
                - "sha:${{github.sha}}"
            - type: "count"
              name: "some_project_or_repo.tests.failed_count"
              value: ${{steps.run-tests.outputs.numFailedTests}}
              host: ${{ github.repository_owner }}
              tags:
                - "project:${{ github.repository }}"
                - "branch:${{ github.head_ref }}"
                - "sha:${{github.sha}}"
            - type: "count" # is this right?
              name: "some_project_or_repo.tests.start_time"
              value: ${{steps.run-tests.outputs.startTime}}
              host: ${{ github.repository_owner }}
              tags:
                - "project:${{ github.repository }}"
                - "branch:${{ github.head_ref }}"
                - "sha:${{github.sha}}"
      - name: Report Failures
        if: failure()
        uses: masci/datadog@v1
        with:
          api-key: ${{ secrets.DATADOG_API_KEY }}
          events: |
            - title: "Failed Running Tests"
              text: "Something bad happened"
              alert_type: "error"
              host: ${{ github.repository_owner }}
              tags:
                - "project:${{ github.repository }}"
                - "branch:${{ github.head_ref }}"
                - "sha:${{github.sha}}"
